language: php

php:
    - 5.4
    - 5.5
    - 5.6

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install --prefer-source -o

script:
    - bin/phpunit --coverage-text
