language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer require --dev --no-update jakub-onderka/php-parallel-lint
    - composer install --prefer-source -o --no-interaction

script:
    - vendor/bin/parallel-lint src/ test/
    - phpunit --coverage-text
